### ISSUE TITLE
Cannot find data used by reproduce_scripts.sh

### ISSUE THREAD

**Issue by porumbes** [wildmeshing/wildmeshing-toolkit#255]
Hello, I'd like to run `reproduce_scripts.sh`, but I cannot find the data sets referenced in the script. 

I've looked for the `wmtk-data-package.zip`file mentioned in [README.md](https://github.com/wildmeshing/wildmeshing-toolkit#readme), but cannot find the file. Additionally, the build target `wmtk_data_download` downloads some data, but not the data referenced in `reproduce_scripts.sh". 

Can you please point me to the necessary data sets?

**Comment by porumbes** [comment]
Any chance I can get some help finding `wmtk-data-package.zip`?

**Comment by JcDai** [comment]
Hi, sorry for the late reply.
You can get the data via this link: 
https://drive.google.com/drive/folders/1jFdQ77E2_n3EJF5_bPOOMEOxF4dyctjN?usp=sharing
