### ISSUE TITLE
Optimization via Differentiable Functions

### ISSUE THREAD

**Issue by mtao** [wildmeshing/wildmeshing-toolkit#367]
Several applications require optimizing mesh vertex attributes via a differentiable function, so we need to develop an interface for this. These functions should be evaluatable on each top level simplex of a mesh, but be dependent on vertex-based attributes. This is to correspond to a discrete variant of an integrable function.

Say $D$ is the cross product domain of all of our vertex attributes. Then we can say that for a homogeneous $k$-simplicial complex embedded in $D$, a function $f: \Omega^k \rightarrow \mathbb{R}$ is a function over $k$-simplices $\omega^k_j \in \Omega^k \subset 2^D$ that varies as the vertices of the simplicial complex are moved. For a vertex $v_i \in \Omega^0 \cap \mathcal{F}(\omega_j^k)$  (i.e a vertex of the $\omega^k_j$ by $\mathcal{F}$ being the facet operator) we can specify 
$\omega^k_j$ as a function of $v_i$, then we can write $f$ in terms of vertices:
$$f(\omega^k_j(v_i))$$
and therefore optimize a vertex according to
$$\min_{v_i} f(\Omega^k) = \sum_{j: v_i \in \mathcal{F}(\omega^k_j)}  f(\omega^k_j(v_i))$$
and if $f$ is differentiable with respect to $v_i$ we can optimize our mesh by moving $\Omega_0$ around with differentiable optimization processes like gradient descent or newton's method.

What we need are:
* An interface for `Function` that can be optimized discretely
* An interface for a `DifferentiableFunction` that can be optimized differentially
* An internal interface for prototyping using automatic differentiation (`AutodiffFunction`)
* A `VertexSmooth`-like operation that has a function as a parameter (and potentially optimization configuration options) to move vertices around.
* Split and Collapse-like operations that evaluate an energy, perform the topological update, and confirm whether the new configuration reduces energy

**Comment by daniel-zint** [comment]
I guess this is work in progress, so I set it to "in progress".
