### ISSUE TITLE
`embedding` component

### ISSUE THREAD

**Issue by daniel-zint** [wildmeshing/wildmeshing-toolkit#399]
The embedding component creates a mesh of a dimension higher than the input which embeds the input. The input and the scaffold are tagged.

The output of the embedding component can be converted into a multi-mesh using the tags.

**Comment by Zhouyuan-Chen** [comment]
I will open a new branch into this main repository, with the same code, but definitely will be easier to review since I only transfer the embedding part code.

**Comment by Zhouyuan-Chen** [comment]
There are some other things to do
- [ ] transfer TetWild(3D embedding) into this component
- [ ] modify the input file

**Comment by Zhouyuan-Chen** [comment]
this part component has been cancelled.
