### ISSUE TITLE
EdgeSwap does not use invariants

### ISSUE THREAD

**Issue by mtao** [wildmeshing/wildmeshing-toolkit#401]
EdgeSwap still has manual before/after and it needs to use invariants.
Giving to @daniel-zint because the invariants that need to be built are ones that he derived I think?

**Comment by daniel-zint** [comment]
TODO:
* [ ] Use `ValidTupleInvariant` and `InteriorEdgeInvariant`
* [ ] Add `MinIncidentValenceInvariant`
* [ ] Add `EdgeSwapBase` which takes care of the above mentioned invariants
* [ ] Rename `EdgeSwap` to `EdgeSwapValence`
