### ISSUE TITLE
refactor smoothing for boundary/interior vertex

### ISSUE THREAD

**Issue by yunfanzhou** [wildmeshing/wildmeshing-toolkit#455]
It is creating a BoundaryVertexSmooth class that will be a special case of VertexSmoothing.
The boundary handling will use the multi-mesh definition. Starting with the main uv mesh (the cut mesh) for a vertex on the boundary using the multimesh `sibling` implementation one can sum up the one-ring differentiable energy on both sides of a seam centered at the corresponding vertices. And the uv-position update will be done automatically on both sides of the seam given multi-mesh implementation, so are the invariants check.
The major refactoring to the current VertexSmoothUsingEnergy class is making the smooth process generic (do not discriminate on whether a vertex is a boundary vertex here; move the special handling to my case-specific AdaptiveTessSmoothVertex class)

**Comment by daniel-zint** [comment]
Please add a description.

**Comment by yunfanzhou** [comment]
- [ ] add boundary_smooth parameter to smooth base class settings 
- [ ] based on the boundary_smooth parameter, add InteriorVertex invariants in the InvariantsCollection
- [ ] change derived class to use the new convention with boundary_smooth in InvariantsCollection
- [ ] rename Smooth functions to clarity it is on TriMesh <-> EdgeMesh
