### ISSUE TITLE
Improve semantics of functions to clarify what simplex they operate on

### ISSUE THREAD

**Issue by mtao** [wildmeshing/wildmeshing-toolkit#456]
Currently our Function class is ambiguous on whether it operates on a single simplex, or on a one ring neighborhood.
Instead we should specify a `PerSimplexFunction` and `OneRingFunction` like interface (similarly for DifferentiablePerSimplexFunction` and `DifferentiableOneRingtFunction`). 
```
Settings {
  std::unique_ptr<DifferentiablePerSimplexFunction> function = std::make_unique<AMIPS2D>(...);
};

run_gradient_descent(Settings& settings) {
    DifferentiableFunction func(settings.mesh, settings.function);
   Eigen::Vector2d duv = func.get_gradient(tuple);
}

```

Typical functions like volume or AMIPS or valence should be derived from `PerSimplex` variants, and the system should automatically create `OneRing` versions when evaluating gradients and hessians for optimization.

This works because the `OneRing` variants should hold a reference to the `PerSimplex` versions, which wrap internal summations (such as aadding over all of the triangles around a vertex to obtain the gradient of a vertex).

**Comment by yunfanzhou** [comment]
- [ ] adapt current Function and DifferentiableFunction class to Function and LocallyDifferentiableFunction class
- [ ] add PerSimplexFunction and DifferentiablePerSimplexFunction that inherits from it
- [ ] add a handle of DifferentiablePerSimplexFunction in LocallyDifferentiableFunction. Add function of get_one_ring_* and get_sum_* functions in LocallyDifferentiableFunction
- [ ] change the function handles in smooth settings to new LocallyDifferentiabelFunction
