### ISSUE TITLE
Add `simplex::vertices(const Simplex& s)`

### ISSUE THREAD

**Issue by daniel-zint** [wildmeshing/wildmeshing-toolkit#478]
Very often, we need all vertices of some simplex, e.g. all vertices in a triangle. Additionally, the vertices usually need to be sorted. Therefore, we cannot just use `simplex::boundary`.

- [x] implement `simplex::vertices(const Simplex& s)`
- [x] document the function
- [x] write tests
- [x] Use it in `EdgeSwapValence::execute` and `MinIncidentValenceInvariant::is_greater_min_valence`
- [x] Generalize to `face_single_dimension`
- [x] Test generalization
- [x] Generalize documentation

**Comment by mtao** [comment]
could this be generalized to `faces_single_dimension` ? I don't mind keeping the current alias, but finding all of the faces with a given prescribed dimension is pretty common / useful.
