### ISSUE TITLE
2d-1d multimesh application framework

### ISSUE THREAD

**Issue by JcDai** [wildmeshing/wildmeshing-toolkit#503]
Add topology preservation on child edgemesh (and geometry preservation) for isotropic remeshing.

- [x] register "tagged" edgemesh as child mesh for the parent trimesh
- [x] add invariant that disallow two vertices on the child mesh to merge when collapsing an edge that is not existing on the child mesh.
- [ ] add unit tests, check if multimesh operations and invariants work

**Comment by daniel-zint** [comment]
Please link the corresponding branch or PR.
