### ISSUE TITLE
refactoring cofaces_single_dimension

### ISSUE THREAD

**Issue by yunfanzhou** [wildmeshing/wildmeshing-toolkit#514]
Underlying API should use tuples

**Comment by mtao** [comment]
Refactor will be done in three steps:
- [] moving responsibility for simplex comparison out of the Mesh class to allow for a more generic implementation of the comparisions
- [] implementation of a faces function that preserves a specific lower dimensional face (this allows for exploration of exploration of faces bounded by two simplices wrt the faces partial ordering)
- [] cofaces-single-dimension that uses top_dimension_cofaces -> uses bounded faces function to start exploring cofaces
