### ISSUE TITLE
attribute swap buffer 

### ISSUE THREAD

**Issue by yunfanzhou** [wildmeshing/wildmeshing-toolkit#567]
For some pipelines we would like to have two copies of an attribute to store an old state and a current state. There are a few potential ways to implement this (like with [checkpointing](https://github.com/wildmeshing/wildmeshing-toolkit/pull/337), but the easiest way is to just store two attributes and compare them between operations

**Comment by mtao** [comment]
this is redundant with https://github.com/wildmeshing/wildmeshing-toolkit/pull/579
