### ISSUE TITLE
Can not find the 'app' folder within 'build' folder after cmake and make process

### ISSUE THREAD

**Issue by NINGYURICHARD** [wildmeshing/wildmeshing-toolkit#735]
I followed the Installation method step by step on WSL, and finally there is no error output just a few warnings. However, when I wanted to run some examples, I could not find the 'app' folder and the remeshing_app or qslim_app file. The 'build' folder only contains these following files.
![image](https://github.com/wildmeshing/wildmeshing-toolkit/assets/74522792/00968f74-b264-4c50-a46a-dd0a46fc169c)

Could you please help me tackle this problem? Thank you very much!

**Comment by Zhouyuan-Chen** [comment]
Hey! I am not sure if I understand it correctly. Suppose you want to run the application, you may need to run the `wmtk_app` file.

For example, if you want to run isotropic_remeshing. You could run it this way:

`./wmtk_app -j your_json_file.json`

In the json file, you should specify the name of the component, the parameters and so on. Have a look at your interested component's file, there should be an example json file. If you still have trouble, please let me know. :)

**Comment by NINGYURICHARD** [comment]
Thanks for your reply! Yes, I want to run the application especially the isotropic_remeshing. Because I am just a beginner of c++, I still have some problems. As for json file, I directly choose 'wildmeshing-toolkit/components/wmtk_components/isotropic_remeshing/wmtk/components/isotropic_remeshing/isotropic_remeshing_example.json'. I copy the json file to 'wildmeshing-toolkit/build', and download the '120628.stl' also in 'build' folder as my input file. Then I modify the json file as follow:
![image](https://github.com/wildmeshing/wildmeshing-toolkit/assets/74522792/d3047740-0a90-45ff-9637-e1688f50fe4d)

and run ' ./wmtk_app -j isotropic_remeshing_example.json' in 'build' folder on WSL. However, it outputs the following errors:
![image](https://github.com/wildmeshing/wildmeshing-toolkit/assets/74522792/85934558-3de7-483d-81e9-23a033675756)

I have no idea how to tackle it. Could you please help me solve this problem? Thank you very much!

**Comment by Zhouyuan-Chen** [comment]
you should put your model file into the build folder. 
input should be a .hdf5 or .msh file. so you should have a .hdf5 or .msh file as an input.
the output is fine, just give any name you want. the output is .hdf file, and you need `paraview` to look at the result.
there is an example from unit tests
```
    "components": [
        {
            "input": {
                "file": "YOUR_INPUT_NAME",
                "name": "mesh"
            }
        },
        {
            "isotropic_remeshing": {
                "attributes": {
                    "position": "vertices"
                },
                "input": "mesh",
                "iterations": 2,
                "length_rel": 1,
                "lock_boundary": true,
                "output": "test"
            }
        },
        {
            "output": {
                "input": "test",
                "file": "YOUR_OUTPUT_NAME",
                "attributes": {
                    "position": "vertices"
                }
            }
        }
```

**Comment by NINGYURICHARD** [comment]
Thank you very much! Your suggestion works for me. May I ask if there is any local remeshing example for 3D objects (tetrahedral mesh)? I found the examples in unit_test are mainly the triangle mesh. Thanks!

**Comment by Zhouyuan-Chen** [comment]
Yeah... The 3D remeshing component is still under construction and has not merged into the main branch. I believe we will publish it later.

**Comment by NINGYURICHARD** [comment]
Thank you very much!
