### ISSUE TITLE
Confusing 'n_tets'

### ISSUE THREAD

**Issue by jiangzhongshi** [wildmeshing/wildmeshing-toolkit#9]
https://github.com/wildmeshing/wildmeshing-toolkit/blob/93d25d416e3807c1f0f4aea5f509eeaa34607fc3/src/TetMesh.h#L255-L258

This function indicates the number of tetrahedra, but not accounting for the removed ones, maybe we need a new name.

This is more similar to `capacity` in std language.

**Comment by Yixin-Hu** [comment]
Who added this function?
